athena-scripts/process_scripts/ipv_cri_ftof_config.json
iac/resources/raw.yml

-- added remaining f2f events which are showing as complete in production txma
-- added f2f event to f2f crawler defintion

No int test/dac 1383 f2f events

---

athena-scripts/process_scripts/ipv_cri_ftof_config.json
iac/resources/raw.yml

- f2f product family tables, created fixed schemas

No int test/dac 1635 f2f fixed raw schema tables

---

athena-scripts/dml/insert_into/ipv_identity_issued.sql
athena-scripts/process_scripts/ipv_journey_config.json
iac/resources/raw.yml
iac/resources/stage.yml

introduction of event ipv_identity_issues

No int test/dac 1654 ipv identity issued

---

iac/resources/global.yml
iac/resources/redshift.yml

This PR has been created to fix ec2 Session Manager connectivity issues.

Ec2 access ssm

---

athena-scripts/process_scripts/ipv_cri_fraud_config.json

turned event processing off for: ipv_fraud_cri_third_party_request_ended

updated fraud config

---

iac/resources/pipeline.yml

This PR is to update the IAM policies we have for analysts. Also, these inline policies will be created only in Production environment.

updated IAM policy for analysts

---

src/handlers/cognito-quicksight-access/handler.spec.ts
src/handlers/cognito-quicksight-access/handler.ts
src/handlers/quicksight-sync-users/handler.ts
src/handlers/test-support/handler.spec.ts

- Set quicksight initial path to dashboards page
- Respond with HTML containing request id in case of lambda error
- Extract getting code logic into a function to simplify error handling

Quicksight access improvements

---

iac/quicksight-access/resources/quicksight-access.yml

This PR is to configure WAF ACL rules for Cognito user pool.

waf config for cognito pool

---

iac/quicksight-access/resources/quicksight-access.yml

1. Fixes error deploying the quicksight access stack to non quicksight environments

Add conditions to WAF resources

---

iac/quicksight-access/resources/quicksight-access.yml

- Enable SES emails in dev and production
- Add invitation and verification email templates

Create SES configuration for Cognito

---

iac/quicksight-access/resources/quicksight-access.yml

- Remove UnusedAccountValidityDays

Dev quicksight access stack fix

---

iac/quicksight-access/resources/pipeline.yml

This PR is to update the quicksight pipeline role.

updated prod qsa role

---

athena-scripts/raw_stage_optimisation_solution/configuration_rules/raw_to_stage_config_rules.json
scripts/athena-upload.sh

configuration rules file which will drive the raw->stage optimisation solution
update to s3 file upload bash script

No int test/dac 2294 raw stage configuration rules

---

iac/main/resources/state-machine.yml
statemachine/txma_raw_layer_consolidated_schema_processing.asl.json

adding raw->stage optimisation glue job to step function

added raw to stage glue job to orchestration step function

---

athena-scripts/process_scripts/ipv_journey_config.json

enabled IPV_IDENTITY_ISSUED

---

.github/workflows/pull-request-deploy-and-test.yml
iac/main/base.yml
iac/main/resources/global.yml
iac/main/resources/redshift.yml
package-lock.json
package.json
scripts/build-lambdas.sh
src/handlers/quicksight-add-users/handler.spec.ts
src/handlers/redshift-rotate-secret/database-access.ts
src/handlers/redshift-rotate-secret/handler.spec.ts
src/handlers/redshift-rotate-secret/handler.ts
src/shared/clients.ts
src/shared/utils/utils.spec.ts
src/shared/utils/utils.ts

- Add redshift-rotate-secret lambda handler
- Add IaC code for lambda and related resources
- Add new ensureDefined util to utils
- Remove some duplicated code from quicksight-add-users handler
- Add @aws-sdk/client-secrets-manager dependency and client in clients.ts
- Add knex and pg dependencies for redshift access
- Add some external packages to esbuild in build-lambdas script as a result of the new knex and pg dependencies

DAC-2203 Secret not scheduled for rotation

---

iac/main/resources/redshift.yml

- Make rotation schedule depend on lambda permission

Secret rotation fixes

---

iac/main/resources/redshift.yml

- Temporarily remove permissions boundary

Secret rotation permissions boundary fix

---

iac/main/resources/global.yml

- Use If for conditional policy instead of Condition

Cross Account Data Sync Fix

---

iac/main/base.yml
iac/main/resources/cross-account.yml
src/handlers/cross-account-transfer/handler.ts

- Add IaC for cross account lambda, role, VPC and other resources
- Minor changes to cross-account-transfer handler code to remove some TypeScript warnings

DAC-2765 Security work and IaC release for ingest lambda

---

iac/main/resources/cross-account.yml

- Increase lambda memory and timeout
- Add VPC endpoint for S3

Cross account transfer lambda improvements

---

iac/main/resources/cross-account.yml

- Add IsProduction condition to S3 endpoint

Cross account S3 VPC endpoint fix

---

iac/main/resources/redshift.yml

Dynatrace dashboard shows redshift RPU throttled many times. Setting the RPU to a higher value will resolve the issue

rpu changed

---

README.md
iac/main/resources/event.yml

- Remove production preview from UsePlaceholderTxMAQueue condition
- Update README

Configure production preview for real TxMA queue

---

src/handlers/redshift-get-metadata/handler.spec.ts
src/handlers/redshift-get-metadata/handler.ts

- Update handler and tests with fileMetadata property being a JSON string not an object

Redshift get metadata fix

---

src/handlers/redshift-get-metadata/handler.spec.ts
src/handlers/redshift-get-metadata/handler.ts

- Return JSON string instead of object from redshift get metadata
- Correct logger name

Redshift get metadata return string

---

iac/main/resources/manual-reference-data-ingestion.yml
iac/main/resources/stage.yml
src/handlers/s3-send-metadata/handler.spec.ts
src/handlers/s3-send-metadata/handler.ts
src/test-resources/s3-object-creation-notification.json

- Add lambda handler, tests and test resource for s3 send metadata
- Add IaC for new s3 send metadata function

DAC-2923 Manual reference data ingestion pipeline part 2

---

iac/quicksight-access/resources/quicksight-access.yml

- Add quicksight:ListGroups permission to quicksight add users lambda IaC

Quicksight add users permissions fix

---

src/handlers/run-flyway-command/handler.spec.ts
src/handlers/run-flyway-command/handler.ts

- Update lambda to support migrations in subdirectories
- Add new test to cover subdirectory support

Add flyway migrations subdirectory support

---

.github/workflows/run-flyway-command.yml
src/handlers/run-flyway-command/handler.spec.ts
src/handlers/run-flyway-command/handler.ts

- Add clean command option to run flyway command workflow
- Add logic in lambda to ensure clean is disabled in production
- Add tests for new clean logic

Add flyway clean option

---

iac/main/base.yml
iac/main/resources/manual-reference-data-ingestion.yml

- Add IaC for upload policy needed by data-analytics-reference-data repository

DAC-2925 Manual reference data ingestion pipeline part 4

---

iac/main/resources/manual-reference-data-ingestion.yml

- Update role condition so it can be assumed from pull request actions

Update manual reference data upload role condition

---

.github/workflows/add-quicksight-user.yml
scripts/get-quicksight-user-spreadsheet.mjs
src/handlers/quicksight-add-users-from-spreadsheet/handler.spec.ts
src/handlers/quicksight-add-users-from-spreadsheet/handler.ts
src/test-resources/user-spreadsheet-data-gds.json
src/test-resources/user-spreadsheet-data-rp.json

- Update get quicksight user spreadsheet script to get all columns
- Simplify add users from spreadsheet lambda logic after new Quicksight groups column has been added
- Update add users from spreadsheet lambda tests and test data
- Add new RPs to add quicksight user workflow

Quicksight add user updates

---

athena-scripts/raw_stage_optimisation_solution/configuration_rules/raw_to_stage_config_rules.json

Updated the consolidated model to enable the following attributes to be stored within the core table in the staging layer
- event_timestamp_ms
- event_timestamp_ms_formatted

updated config file to include millsec columns

---

iac/main/resources/redshift.yml

increased rpu

---

.github/workflows/quicksight-export.yml
.github/workflows/quicksight-import.yml
iac/quicksight-access/resources/quicksight-access.yml

- Add workflow_call configuration to both workflows
- Allow data-analytics-adm repo to assume lambdas invoke role
- Simplify lambdas invoke role condition repo references

DAC-3252 Add Quicksight import/export workflows to Analysts' repo

---

src/handlers/stepfunction-validate-execution/handler.spec.ts
src/handlers/stepfunction-validate-execution/handler.ts
src/shared/utils/utils.ts

- Add logic in stepfunction validate execution lambda to allow continuation if the current execution started first
- Update and simplify tests for new logic
- Update ensureDefined util to handle any type

Stepfunction validate execution start time

---

iac/main/resources/pipeline.yml
iac/quicksight-access/resources/pipeline.yml

- Move cloudfront and shield permissions from quicksight stack to main stack

Fix deployment in test

---

.cfnlintrc.yml
.github/workflows/deploy-to-aws.yml
.github/workflows/sam-deploy.yml
.github/workflows/test-and-validate.yml
iac/quicksight-access/resources/quicksight-access.yml

- Add role for new data-analytics-quicksight repository to use Update SAM version in workflows
- Add .cfnlintrc.yml file to ignore new warning after SAM version update

DAC-3276 Implement GitHub RP onboarding users using techniques developed for non-event data

---

iac/quicksight-access/resources/quicksight-import-export.yml

- Replace custom policies with managed polices in import and export lambda IaC

DAC-3234 Move to new Quicksight asset bundle IAM policies

---

iac/quicksight-access/resources/quicksight-import-export.yml

Quicksight asset bundle IAM policies fix

---

iac/main/base.yml
iac/main/resources/redshift.yml

- Add IaC for data-analytics-adm repository role
- Add new IsADMEnvironment condition to specify environments where role is needed

Add data-analytics-adm role

---

.github/workflows/deploy-to-aws.yml
.github/workflows/sam-deploy.yml

- Remove unneeded LFS checkouts

DAC-3015 Remove LFS checkouts from GitHub workflows

---

.github/workflows/deploy-to-aws.yml

- Change from v3.9 which was a pre-release version

Change devplatform-upload-action version

---

src/handlers/athena-get-config/handler.spec.ts
src/handlers/athena-get-statement/handler.spec.ts
src/handlers/dlq-to-eventbridge/handler.spec.ts
src/handlers/dlq-to-eventbridge/handler.ts
src/handlers/quicksight-add-users-from-spreadsheet/handler.spec.ts
src/handlers/quicksight-add-users/handler.spec.ts
src/handlers/quicksight-export/handler.spec.ts
src/handlers/quicksight-export/handler.ts
src/handlers/quicksight-import/handler.spec.ts
src/handlers/quicksight-import/handler.ts
src/handlers/redshift-get-metadata/handler.spec.ts
src/handlers/redshift-rotate-secret/handler.spec.ts
src/handlers/run-flyway-command/handler.spec.ts
src/handlers/s3-raw-to-staging/handler.spec.ts
src/handlers/s3-send-metadata/handler.spec.ts
src/handlers/stepfunction-validate-execution/handler.spec.ts
src/handlers/stepfunction-validate-execution/handler.ts
src/handlers/test-support/handler.spec.ts
src/shared/utils/utils.ts
tests/helpers/event-data-helper.ts

- Remove use of deprecated APIs
- Remove other code smells and fix linting errors
- No way was found to make Sonar generate reports other than a paid third party plugin

DAC-2408 Configuration Sonar project properties

---

iac/main/resources/global.yml

- Add permissions for logging service principal to global bucket policy

DAC-1563 Logs are not appearing in logs bucket

---

athena-scripts/raw_stage_optimisation_solution/clean_stage_layer/README.md
athena-scripts/raw_stage_optimisation_solution/clean_stage_layer/clean_stage_layer.py
athena-scripts/raw_stage_optimisation_solution/clean_stage_layer/clean_stage_layer_config.json
athena-scripts/raw_stage_optimisation_solution/splunk_migration/README.md
athena-scripts/raw_stage_optimisation_solution/splunk_migration/dummyconfig.csv
athena-scripts/raw_stage_optimisation_solution/splunk_migration/splunk-data-export-gz.py

Added two scripts with config files and READMEs
1. Clean stage layer of certain events that need to be reprocessed
2. Splunk migration tool

DPT-86 add scripts for manual processes

---

iac/main/resources/pipeline.yml

- Add glue:UntagResource to deploy role glue policy

Add needed deploy role permission

---

iac/main/resources/sustainability.yml

[DPT-610](https://govukverify.atlassian.net/browse/DPT-610)
Creating new S3 bucket only.
Replication rules to be added once destination S3 bucket has been set up 
[DPT-610]: https://govukverify.atlassian.net/browse/DPT-610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DPT-610: adding sustainability bucket

---

iac/main/resources/sustainability.yml

Adding replication configuration to sustainability bucket

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.2__journey_id_fix_dpt_780.sql

Delete the fact /extensions records which had wrong journey id's.

journey_id fix

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.3__async_events_inserts_dpt_769.sql

Configuration of 3  new Async events.

Async events inserts

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.6__rp_changes_dbt_880_888_6_new_insert_update.sql

RP config changes for client id (Mh3SUEDHB74A2SIB_1VAXZKG_iw and gFVZdC1P4b7fobLgsN2eBVmVC8w).

updated/insert new RP DPT 880-888

---

scripts/athena-upload.sh

raw-to-stage folder name fix

---

iac/main/resources/redshift.yml
iac/main/resources/sustainability.yml

add roles to production for sustainability

---

iac/quicksight-access/resources/quicksight-access.yml

- Add new secretsmanager secret for google service account
- Add kms key to protect secretsmanager secret
- Add kms and secretsmanager permissions to sync role

DPT-910 Add check spreadsheet workflow to data analytics quicksight

---

.github/workflows/code-quality-sonarcloud.yml

- Switch to new sonar action as old one is deprecated
- See https://github.com/SonarSource/sonarcloud-github-action

DPT-1031 Update sonar action

---

README.md
iac/main/base.yml
iac/main/resources/event.yml

Ticket Number: [DPT-944](https://govukverify.atlassian.net/browse/DPT-944) 🎫
- Update UsePlaceholderTxMAQueue condition in IaC
- Update documentation in README
[DPT-944]: https://govukverify.atlassian.net/browse/DPT-944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DPT-944 Activate DAP staging environment

---

.github/workflows/deploy-to-aws.yml
.github/workflows/sam-deploy.yml
.github/workflows/test-and-validate.yml
README.md
iac/main/resources/global.yml
iac/main/resources/redshift.yml

Ticket link: https://govukverify.atlassian.net/browse/DPT-949
- Update SAM CLI version in workflow files
- Remove redundant ToPort and FromPort properties causing W3687
- See https://github.com/aws-cloudformation/cfn-lint/blob/main/docs/rules.md

DPT-949 Update SAM CLI version in GitHub Actions

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.10__proc_fact_user_journey_event_refactored_upsert_dpt_1082.sql
redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.9__proc_event_extensions_refactored_upsert_dpt_1082.sql

DPT -1082 , this was a bug where extensions for already ingested events were not reflecting correctly in the conform layer.

No int test/dpt 1082 extensions fix

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.14__rp_changes_dpt_1293_1295_co_jobs_Clean_Heat_insert_update.sql

Two new RP (Civil Service Jobs  and Manage Clean Heat Market Mechanism) going live.

updated to RP prod

---

redshift-scripts/setup_process_refactored/redshift_setup_process_scripts_refactored.sql

https://govukverify.atlassian.net/jira/software/c/projects/DPT/boards/604?assignee=712020%3A45f9d3ac-fef5-4372-97b9-620ad222d6c2&selectedIssue=DPT-1055
Adds script to set up external schema in redshift for sustainability

add sustainability set up process script

---

redshift-scripts/flyway/flyway.conf

https://govukverify.atlassian.net/jira/software/c/projects/DPT/boards/604?assignee=712020%3A45f9d3ac-fef5-4372-97b9-620ad222d6c2&selectedIssue=DPT-1055

add sustainability to flyway

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.18__rp_changes_dpt_1373_1374_RP_insert_update.sql

One new RP (DPT-1374) and update to one of the RP(DPT-1373).

No int test/dpt 1373 1374 rp changes

---

iac/main/resources/redshift.yml
redshift-scripts/flyway/lib/flyway-commandline-10.7.2-linux-x64.tar.gz
redshift-scripts/flyway/lib/flyway-commandline-11.8.2-linux-x64.tar.gz

- Give flyway lambda more memory
- Update flyway-commandline library version

Run flyway improvements

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.19__Mobile_ID_Check_App_V2_events_inserts_dpt_663.sql

DPT-654 Mobile | ID Check APP v2 | STS events

No int test/dpt 663 mobile id check app v2 events

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.20__Account_Auth_MGMT_events_inserts_dpt_1385.sql

deploying auth MGMT event.
https://govukverify.atlassian.net/browse/DPT-1385

No int test/dpt 1385 account auth mgmt events

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.21__AUTH_LOG_OUT_SUCCESS_clean_up_dpt_1482.sql

removing event id's for AUTH_LOG_OUT_SUCCESS so it can be reloaded.

No int test/dpt 1482 auth log out success clean up

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.25__rp_changes_dpt-1621-1622-1625-1626-1661_RP_insert_update.sql

6 new RP changes dpt 1621 1622 1625 1626 1661

No int test/dpt 1621 1622 1625 1626 1661 rp changes

---

iac/quicksight-access/base.yml
iac/quicksight-access/resources/alerting.yml

https://govukverify.atlassian.net/browse/DPT-1689
- Add cloudwatch alert, sns topic, and chatbot configuration and role to new quicksight access alerting.yml file
- Add variables for slack workspace and channel ids to quicksight access base.yml

DPT-1689 Create CloudWatch alarm for QuickSight SPICE capacity

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.36__DWP_KBV_GLOBAL_LOGOUT_events_inserts_dpt_1358_1861.sql

Enabling 6 new events i.e. 
IPV_DWP_KBV_CRI_START
IPV_DWP_KBV_CRI_VC_ISSUED
IPV_DWP_KBV_CRI_THIN_FILE_ENCOUNTERED
IPV_DWP_KBV_CRI_ABANDONED
HOME_GLOBAL_LOGOUT_REQUESTED
AUTH_GLOBAL_LOG_OUT_SUCCESS
*********************************************
https://govukverify.atlassian.net/browse/DPT-1357
https://govukverify.atlassian.net/browse/DPT-1857

No int test/dpt 1358 1861 dwp kbv global logout insert

---

redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.38__AUTH_OIDC_TOKEN_GENERATED_events_inserts_dpt_1880.sql
redshift-scripts/flyway/migrations/dap_txma_reporting_db_refactored/V5.39__rp_changes_dpt-1955_bug_RP_update.sql

1) enabling new event AUTH_OIDC_TOKEN_GENERATED
2)Fixing bug for RP IJ_TuVEgIqAWT2mCe9b5uocMyNs as it display name and client name wasn't update in conform layer.

No int test/dpt 1880 auth OIDC token generated insert

---

raw-to-stage/raw_to_stage_etl/strategies/scheduled_strategy.py
raw-to-stage/tests/processor/test_raw_to_stage_processor.py

Made some changes to test pipeline. Now reverting those to fix pipeline.

DPT-1909 Reverting changes to fix pipeline

---

scripts/build-and-deploy-etl.sh

Fix for issue shown in screenshot to escape single quote present in commit messages
https://github.com/govuk-one-login/data-analytics-platform/actions/runs/17267363896/job/49002739527

fix pipeline

---

raw-to-stage/raw_to_stage_etl/strategies/scheduled_strategy.py

Added small change to log to test DPT-1909 (to be removed later)

DPT-1909 Changing log to test CICD pipeline

---

.github/workflows/deploy-to-aws.yml

fail deployment if etl upload fails

fail deployment if etl upload fails

---

raw-to-stage/raw_to_stage_etl/strategies/scheduled_strategy.py
raw-to-stage/tests/processor/test_raw_to_stage_processor.py

- Reverted change I had previously made to make unit tests fail, to make unit tests pass again
- Reverted change I had made to log message (also to validate success scenario for DPT-1909)

DPT-1909 Fix unit tests and change logs to validate success scenario

---

tests/Dockerfile

Codepipeline needed to be updated with new ECR url, this triggers the test again

trigger cicd pipeline to use new test

---

iac/main/resources/event.yml

enable event source mapping

---

iac/core/base.yml
iac/main/base.yml
iac/main/resources/redshift.yml
iac/quicksight-access/base.yml

https://govukverify.atlassian.net/browse/DPT-2247?search_id=01399853-68e7-4ca6-aa47-63b5912d854d
https://govukverify.atlassian.net/jira/software/c/projects/DPT/boards/604?assignee=712020%3A45f9d3ac-fef5-4372-97b9-620ad222d6c2&assignee=712020%3A7f17c4d1-32fe-4ef9-bd6e-55ee7774eceb&selectedIssue=DPT-2243
fix prod preview deployment
change flyway to x86_64 arch

Dpt 2243 fix prod preview deployment

---

README.md
iac/quicksight-access/resources/quicksight-access.yml

https://govukverify.atlassian.net/browse/DPT-2034

DPT-2240 remove old apigw

---

iac/main/base.yml
iac/main/resources/event.yml

Remove placeholder queue in prod preview and enable event source mapping

Dpt 2243 fix prod preview event source mapping

---

src/handlers/txma-event-consumer/handler.spec.ts
src/handlers/txma-event-consumer/handler.ts

https://govukverify.atlassian.net/browse/DPT-2267

remove debug logs from DAP lambda
